### ISSUE TITLE
CFFI char* cast warning

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/pyOKFrontPanel#2]
Please post the warning so I can investigate.

**Comment by Neverhorst** [comment]
C:\Anaconda3\envs\qudi\lib\site-packages\pyokfrontpanel-4.5.6a2-py3.6-win-amd64.egg\okfrontpanel\fp.py:600: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  err = lib.okFrontPanel_ReadFromBlockPipeOut(self._handle, epAddr, blockSize, length, data_ref)

**Comment by drogenlied** [comment]
Try again with the latest version.

**Comment by Neverhorst** [comment]
Good job. No warning anymore when pulling data with okFrontPanel API.
